import {Alert,Avatar,Box,Button,CircularProgress,Dialog,DialogActions,DialogContent,DialogTitle,Stack,Typography} from '@mui/material';
import {DeleteRounded,PhotoCameraRounded} from '@mui/icons-material';
import {useEffect,useMemo,useState} from 'react';
import {actualizarMiFotoPerfilServidor,eliminarMiFotoPerfilServidor,obtenerMiFotoPerfilServidor} from '../../api/fotoPerfilServidorApi';
const MAX_BYTES=2*1024*1024; const TIPOS=['image/jpeg','image/jpg','image/png','image/webp'];
function inicial(nombre){return String(nombre||'?').trim().charAt(0).toUpperCase();}
function leerArchivo(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const resultado=String(reader.result||'');resolve({nombre:file.name,tipo:file.type,base64:resultado.split(',')[1]||''});};reader.onerror=()=>reject(new Error('No fue posible leer la fotografía.'));reader.readAsDataURL(file);});}
export default function FotoPerfilServidor({token,nombre='',fotoPerfilUrl='',onActualizada,editable=true,size=128}){
  const[datos,setDatos]=useState({nombre,fotoPerfilUrl}); const[archivo,setArchivo]=useState(null); const[vistaPrevia,setVistaPrevia]=useState(''); const[abierto,setAbierto]=useState(false); const[cargando,setCargando]=useState(false); const[error,setError]=useState(''); const[mensaje,setMensaje]=useState('');
  useEffect(()=>{setDatos(actual=>({...actual,nombre:nombre||actual.nombre,fotoPerfilUrl:fotoPerfilUrl||actual.fotoPerfilUrl}));},[nombre,fotoPerfilUrl]);
  useEffect(()=>{if(!token||!editable)return;let activo=true;obtenerMiFotoPerfilServidor(token).then(r=>{if(activo)setDatos({nombre:r?.nombre||nombre,fotoPerfilUrl:r?.fotoPerfilUrl||''});}).catch(()=>{});return()=>{activo=false;};},[token,editable,nombre]);
  const imagenVisible=useMemo(()=>vistaPrevia||datos.fotoPerfilUrl||'',[vistaPrevia,datos.fotoPerfilUrl]);
  async function seleccionar(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;setError('');setMensaje('');if(!TIPOS.includes(file.type)){setError('Solo se permiten fotografías JPG, JPEG, PNG o WEBP.');return;}if(file.size>MAX_BYTES){setError('La fotografía no puede superar 2 MB.');return;}try{setArchivo(await leerArchivo(file));setVistaPrevia(URL.createObjectURL(file));setAbierto(true);}catch(err){setError(err.message);}}
  function cerrar(){if(cargando)return;if(vistaPrevia)URL.revokeObjectURL(vistaPrevia);setAbierto(false);setArchivo(null);setVistaPrevia('');}
  async function guardar(){if(!archivo||!token)return;setCargando(true);setError('');try{const r=await actualizarMiFotoPerfilServidor(token,archivo);setDatos(actual=>({...actual,fotoPerfilUrl:r.fotoPerfilUrl}));setMensaje('La fotografía fue actualizada correctamente.');if(onActualizada)onActualizada(r);cerrar();}catch(err){setError(err?.message||'No fue posible actualizar la fotografía.');}finally{setCargando(false);}}
  async function eliminar(){if(!token||!window.confirm('¿Deseas eliminar tu fotografía de perfil?'))return;setCargando(true);setError('');setMensaje('');try{const r=await eliminarMiFotoPerfilServidor(token);setDatos(actual=>({...actual,fotoPerfilUrl:''}));setMensaje('La fotografía fue eliminada.');if(onActualizada)onActualizada(r);}catch(err){setError(err?.message||'No fue posible eliminar la fotografía.');}finally{setCargando(false);}}
  return <><Stack spacing={1.5} alignItems="center"><Avatar src={imagenVisible||undefined} alt={datos.nombre} sx={{width:size,height:size,fontSize:size*.35,fontWeight:900}} imgProps={{referrerPolicy:'no-referrer'}}>{inicial(datos.nombre)}</Avatar>{editable&&<Stack direction={{xs:'column',sm:'row'}} spacing={1}><Button component="label" variant="contained" startIcon={<PhotoCameraRounded/>} disabled={cargando}>{datos.fotoPerfilUrl?'Cambiar foto':'Subir foto'}<input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={seleccionar}/></Button>{datos.fotoPerfilUrl&&<Button color="error" variant="outlined" startIcon={<DeleteRounded/>} onClick={eliminar} disabled={cargando}>Eliminar</Button>}</Stack>}{cargando&&<CircularProgress size={24}/>} {error&&<Alert severity="error" sx={{width:'100%'}}>{error}</Alert>} {mensaje&&<Alert severity="success" sx={{width:'100%'}}>{mensaje}</Alert>} {editable&&<Typography variant="caption" color="text.secondary" textAlign="center">JPG, PNG o WEBP. Máximo 2 MB.</Typography>}</Stack><Dialog open={abierto} onClose={cerrar} fullWidth maxWidth="xs"><DialogTitle>Confirmar fotografía</DialogTitle><DialogContent><Box display="grid" sx={{placeItems:'center'}} py={2}><Avatar src={vistaPrevia||undefined} sx={{width:220,height:220}}/></Box></DialogContent><DialogActions><Button onClick={cerrar} disabled={cargando}>Cancelar</Button><Button variant="contained" onClick={guardar} disabled={cargando||!archivo}>{cargando?'Guardando...':'Guardar fotografía'}</Button></DialogActions></Dialog></>;
}
