import {Alert,Box,Button,Card,CardContent,Divider,Grid,MenuItem,Stack,TextField,Typography} from '@mui/material';
import BadgeRounded from '@mui/icons-material/BadgeRounded';import HotelRounded from '@mui/icons-material/HotelRounded';import UploadFileRounded from '@mui/icons-material/UploadFileRounded';import PictureAsPdfRounded from '@mui/icons-material/PictureAsPdfRounded';
import {useEffect,useState} from 'react';import PageHeader from '../components/PageHeader';import {useAuth} from '../auth/AuthContext';
import {obtenerConfiguracionImpresion,obtenerDatosGeneracionImpresion,obtenerImagenPlantillaImpresion,guardarPlantillaImpresionApi} from '../api/impresionRetiroApi';
import {generarEscarapelasPdf,generarEscarapelaPdf,generarHabitacionesPdf,generarHabitacionPdf} from '../utils/pdfImpresionRetiro';

function archivoBase64(file){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok({nombre:file.name,tipo:file.type,base64:r.result});r.onerror=no;r.readAsDataURL(file);});}
function Plantilla({titulo,tipo,config,token,puede,onSaved}){
 const [file,setFile]=useState(null),[w,setW]=useState(config?.anchoCm||''),[h,setH]=useState(config?.altoCm||''),[err,setErr]=useState('');
 useEffect(()=>{setW(config?.anchoCm||'');setH(config?.altoCm||'')},[config]);
 async function guardar(){try{setErr('');if(!file)throw new Error('Seleccione una imagen.');const a=await archivoBase64(file);await guardarPlantillaImpresionApi(token,tipo,a,w,h);setFile(null);await onSaved();}catch(e){setErr(e.message);}}
 return <Card variant="outlined"><CardContent><Stack spacing={2}><Typography variant="h6" fontWeight={900}>{titulo}</Typography>{config?.nombre&&<Alert severity="success">Configurada: <b>{config.nombre}</b> · {config.anchoCm} × {config.altoCm} cm</Alert>}{err&&<Alert severity="error">{err}</Alert>}<Button component="label" variant="outlined" startIcon={<UploadFileRounded/>} disabled={!puede}>Seleccionar imagen<input hidden type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/></Button>{file&&<Typography variant="caption">{file.name}</Typography>}<Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField label="Ancho (cm)" type="number" value={w} onChange={e=>setW(e.target.value)} disabled={!puede}/><TextField label="Alto (cm)" type="number" value={h} onChange={e=>setH(e.target.value)} disabled={!puede}/></Stack><Button variant="contained" onClick={guardar} disabled={!puede||!file}>Guardar plantilla</Button></Stack></CardContent></Card>
}
export default function ImpresionRetiro(){
 const {token,tienePermiso}=useAuth(),[cfg,setCfg]=useState({}),[datos,setDatos]=useState({caminantes:[],habitaciones:[]}),[cam,setCam]=useState(''),[hab,setHab]=useState(''),[err,setErr]=useState('');
 const puedeCfg=tienePermiso('SISTEMA_CONFIGURAR_PLANTILLAS_IMPRESION'),puedeGen=tienePermiso('SISTEMA_GENERAR_ESCARAPELAS_HABITACIONES');
 async function cargar(){try{setErr('');const [c,d]=await Promise.all([obtenerConfiguracionImpresion(token),obtenerDatosGeneracionImpresion(token)]);setCfg(c);setDatos(d);}catch(e){setErr(e.message)}}
 useEffect(()=>{cargar()},[token]);
 async function plantilla(tipo){return obtenerImagenPlantillaImpresion(token,tipo)}
 async function ejecutar(fn){try{setErr('');await fn()}catch(e){setErr(e.message)}}
 return <Box><PageHeader titulo="Escarapelas y habitaciones" subtitulo="Configura las plantillas y genera PDFs listos para impresión." icono={<BadgeRounded/>}/><Stack spacing={2.5}>{err&&<Alert severity="error">{err}</Alert>}<Grid container spacing={2}><Grid size={{xs:12,md:6}}><Plantilla titulo="Plantilla de escarapela" tipo="escarapela" config={cfg.escarapela} token={token} puede={puedeCfg} onSaved={cargar}/></Grid><Grid size={{xs:12,md:6}}><Plantilla titulo="Plantilla de habitación" tipo="habitacion" config={cfg.habitacion} token={token} puede={puedeCfg} onSaved={cargar}/></Grid></Grid><Divider/>
 <Grid container spacing={2}><Grid size={{xs:12,md:6}}><Card variant="outlined"><CardContent><Stack spacing={2}><Typography variant="h6" fontWeight={900}>Escarapelas</Typography><Typography variant="body2" color="text.secondary">{datos.caminantes?.length||0} caminantes activos.</Typography><Button variant="contained" startIcon={<PictureAsPdfRounded/>} disabled={!puedeGen||!cfg.escarapela?.fileId} onClick={()=>ejecutar(async()=>generarEscarapelasPdf(datos.caminantes,await plantilla('escarapela')))}>Generar todas</Button><TextField select label="Caminante" value={cam} onChange={e=>setCam(e.target.value)}>{(datos.caminantes||[]).map(c=><MenuItem key={c.id} value={c.id}>{c.nombre}</MenuItem>)}</TextField><Button variant="outlined" disabled={!puedeGen||!cam||!cfg.escarapela?.fileId} onClick={()=>ejecutar(async()=>{const c=datos.caminantes.find(x=>x.id===cam);await generarEscarapelaPdf(c,await plantilla('escarapela'))})}>Generar individual</Button></Stack></CardContent></Card></Grid>
 <Grid size={{xs:12,md:6}}><Card variant="outlined"><CardContent><Stack spacing={2}><Typography variant="h6" fontWeight={900}>Marcación de habitaciones</Typography><Typography variant="body2" color="text.secondary">{datos.habitaciones?.length||0} habitaciones.</Typography><Button variant="contained" startIcon={<HotelRounded/>} disabled={!puedeGen||!cfg.habitacion?.fileId} onClick={()=>ejecutar(async()=>generarHabitacionesPdf(datos.habitaciones,await plantilla('habitacion')))}>Generar todas</Button><TextField select label="Habitación" value={hab} onChange={e=>setHab(e.target.value)}>{(datos.habitaciones||[]).map(h=><MenuItem key={h.id} value={h.id}>Habitación {h.habitacion}</MenuItem>)}</TextField><Button variant="outlined" disabled={!puedeGen||!hab||!cfg.habitacion?.fileId} onClick={()=>ejecutar(async()=>{const h=datos.habitaciones.find(x=>x.id===hab);await generarHabitacionPdf(h,await plantilla('habitacion'))})}>Generar individual</Button></Stack></CardContent></Card></Grid></Grid></Stack></Box>
}
